name = "coffee craft"
author = "hackel"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "264a70da335595b8482f465f5a4e1803200dbb3c6688ab5c0895feda513714ef"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
