name = "coffee craft"
author = "hackel"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60a23b399e4c36950a12c38ecf5245c3756ee1c46532f9773d1c6e5474b2210e"

[versions]
forge = "47.4.5"
minecraft = "1.20.1"
